import{a as f,S as p,i as n}from"./assets/vendor-MgecxatS.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const m="https://pixabay.com/api/",g="54266757-223a8fcde2c0e71951b4feb81";function h(i){const r={key:g,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0};return f.get(m,{params:r}).then(o=>o.data)}const c=document.querySelector(".gallery"),l=document.querySelector(".loader");let y=new p(".gallery a",{captionsData:"alt",captionDelay:250});function b(i){const r=i.map(({webformatURL:o,largeImageURL:a,tags:e,likes:t,views:s,comments:u,downloads:d})=>`<li class="gallery-item">
                <a class="fallery-link" href="${a}">
                    <img class="gallery-image" src="${o}" alt="${e}"/>
                    <div class="info">
                      <p><b>Likes:</b> ${t}</p>
                      <p><b>Views</b>${s}</p>
                      <p><b>Comments</b>${u}</p>
                      <p><b>Downloads</b>${d}</p>
                    </div>
                </a>
            </li>`).join("");c.insertAdjacentHTML("beforeend",r),y.refresh()}function L(){c.innerHTML=""}function S(){l.classList.remove("is-hidden")}function w(){l.classList.add("is-hidden")}const q=document.querySelector(".form");q.addEventListener("submit",P);function P(i){i.preventDefault();const r=i.currentTarget.elements["search-text"].value.trim();if(r===""){n.warning({message:"Please enter a search term!",position:"topRight"});return}L(),S(),h(r).then(o=>{if(o.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}b(o.hits)}).catch(o=>{n.error({message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(o)}).finally(()=>{w(),i.target.reset()})}
//# sourceMappingURL=index.js.map
